-- ####################################
-- NamelessAffirmation Official Schema 
-- VERSION: 20240715_v1
--
-- https://namelessaffirmation.com
--
-- Licensed Under MIT.
-- Copyright 2024. NamelessAffirmation. All Rights Reserved.
-- 
-- This will allow you to create a new (empty) 
-- database from scratch to get started. You 
-- should run these in order.
-- ####################################

CREATE TABLE IF NOT EXISTS "staged_messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp DEFAULT (now()),
  "modified_at" timestamp,
  "is_archived" boolean DEFAULT false,
  "is_approved" boolean DEFAULT false,
  "message" text
);